default_env: &default
  adapter: postgresql
  encoding: unicode
  databese: s_schedule

development:
  <<: *default

production:
  <<: *default
  host: dpg-ck23mgg21fec73b77cjg-a
  databese: tripscheduling
  username: tripscheduling
  password: 4t6dFQtqJBN08JDxZTOnyh2FiilMsz1m
