default_env: &default
  adapter: postgresql
  encoding: unicode
  host: dpg-ck227cvhdsdc73efkt6g-a
  databese: s_original_evjm
  username: s_original_evjm_user
  password: Mt1ithCswDwyj0KXhiVsgj7OeKNseTm6

development:
  <<: *default

production:
  <<: *default
  host: dpg-ck227cvhdsdc73efkt6g-a
  databese: s_original_evjm
  username: s_original_evjm_user
  password: Mt1ithCswDwyj0KXhiVsgj7OeKNseTm6
